### ISSUE TITLE
delphix engine password

### ISSUE THREAD

**Issue by g4gps** [jenkinsci/delphix-plugin#10]
Hi
I am raising this to get clarification.
During jenkins configuration, delphix engine password is collected and it might be stored in some file for future jenkins deloyments. 
is this password stored in plain test or somewaht encrypted/masked?

Also, can we have multiple jenkins configuration and restrict one set of users(one development team) accessing details of engines from other set of users(ie another development team)?

thanks in advance.

**Comment by jgebal** [comment]
Ideally the connectivity to Delphix should be managed by Jenkins credentials.
I would also prefer the connections to individual Jetstream to be managed on project/job level not on Jenkins system level.
Putting it at Jenkins plugin configuration level (system) means anyone can create any job to manage any Delphix that is configured.
This is not suitable for enterprise, where one Jenkins can serve to multiple teams across multiple departments in an organization,

**Comment by mcred** [comment]
You're correct that this plugin uses global configuration to store the credentials. If you're looking for something more flexible, take a look at the [Automation Framework](https://github.com/delphix/automation-framework) and example Jenkins file [here](https://github.com/delphix/automation-framework-demo/blob/master/Jenkinsfile). This example uses Jenkins credentials (line 66) to authenticate to the Delphix engine. Each jenkinsfile or pipeline job could use a different credential set per job.
