### ISSUE TITLE
Jenkins Pipeline support

### ISSUE THREAD

**Issue by jgebal** [jenkinsci/delphix-plugin#11]
Hi,
Is the plugin compatible with Jenkins groovy pipeline syntax?
If so, can you provide some examples?
The only description I've found for the plugin was this one:
https://www.delphix.com/blog/jenkins-plugin

The blog however only describes basic config using UI, not Jenkins pipeline scripts.

**Comment by mcred** [comment]
This plugin isn't compatible with pipeline integration. There is another option for integrating Delphix and Jenkins, the [Automation Framework](https://github.com/delphix/automation-framework). It's a more agnostic way to use scripting for Delphix during CI/CD. There is also a demo application with a Jenkins file the uses pipeline syntax [here](https://github.com/delphix/automation-framework-demo/blob/master/Jenkinsfile).

**Comment by jgebal** [comment]
Thank you.
I will look into the resources you've provided.
