### ISSUE TITLE
Delphix Statement of Support

### ISSUE THREAD

**Issue by trane000** [jenkinsci/delphix-plugin#8]
I'm getting the following error setting up Jenkins plugin to Delphix engine 5.3.1.2

1)	Initial SSL Handshake
Jan 25, 2019 3:39:06 PM FINE org.apache.http.impl.execchain.MainClientExec execute
Opening connection {s}->https://delphixt03:443
Jan 25, 2019 3:39:06 PM FINE org.apache.http.impl.conn.DefaultHttpClientConnectionOperator connect
Connecting to delphixt03/1xx.xx.x.xxx:443
Jan 25, 2019 3:39:06 PM FINE org.apache.http.conn.ssl.SSLConnectionSocketFactory createLayeredSocket
Starting handshake
Jan 25, 2019 3:39:06 PM FINE org.apache.http.conn.ssl.SSLConnectionSocketFactory verifyHostname
Secure session established

2)	Getting A Session 
Jan 25, 2019 3:39:06 PM FINE org.apache.http.impl.conn.DefaultHttpClientConnectionOperator connect
Connection established 1xx.xx.xx.xxxx:57398<->1xx.xx.x.xxx:443
Jan 25, 2019 3:39:06 PM FINE org.apache.http.impl.execchain.MainClientExec execute
Executing request POST /resources/json/delphix/session HTTP/1.1
Jan 25, 2019 3:39:06 PM FINE org.apache.http.impl.conn.Wire wire
http-outgoing-9 >> "{"type": "APISession","version": {"type": "APIVersion","major": 1,"minor": 7,"micro": 0}}"

 Response

 Jan 25, 2019 3:39:06 PM FINE org.apache.http.impl.conn.Wire wire
http-outgoing-9 << "[\r][\n]"
Jan 25, 2019 3:39:06 PM FINE org.apache.http.impl.conn.Wire wire
http-outgoing-9 << "{"type":"OKResult","status":"OK","result":{"type":"APISession","version":{"type":"APIVersion","major":1,"minor":7,"micro":0},"locale":null,"client":null},"job":null,"action":null}"
 
3)	Login to Delphix
Jan 25, 2019 3:39:06 PM FINE org.apache.http.impl.execchain.MainClientExec execute
Executing request POST /resources/json/delphix/login HTTP/1.1
Jan 25, 2019 3:39:06 PM FINE org.apache.http.impl.conn.LoggingManagedHttpClientConnection onRequestSubmitted
http-outgoing-9 >> POST /resources/json/delphix/login HTTP/1.1
Jan 25, 2019 3:39:06 PM FINE org.apache.http.impl.conn.Wire wire
http-outgoing-9 >> "{"type": "LoginRequest","username": "c62cd84","password": "xxxxx"}"
 
Response
Jan 25, 2019 3:39:06 PM FINE org.apache.http.impl.conn.Wire wire
http-outgoing-9 << "{"type":"ErrorResult","status":"ERROR","error":{"type":"APIError","details":"No API session has been established.","action":"Create an API session by calling /resources/json/delphix/session.","id":"exception.webservices.session.nosession","commandOutput":null,"diagnoses":null}}"
Jan 25, 2019 3:39:06 PM FINE org.apache.http.impl.conn.LoggingManagedHttpClientConnection onResponseReceived
http-outgoing-9 << HTTP/1.1 200

**Comment by mcred** [comment]
The issue was related to an update in 5.3. The latest version 2.0.4 contains the fix for this issue.
